/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Alejo",
  "tagline": "Complete technical guide to master AI Engineering and AI Architecture",
  "favicon": "img/favicon.ico",
  "url": "https://alejoalvarez.github.io",
  "baseUrl": "/documentation/",
  "organizationName": "alejoalvarez",
  "projectName": "documentation",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/alejoalvarez/Documents/Alejo/documentation/sidebars.js",
          "editUrl": "https://github.com/alejoalvarez/documentation/tree/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/alejoalvarez/Documents/Alejo/documentation/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.png",
    "navbar": {
      "title": "Alejo-Docs",
      "logo": {
        "alt": "Alejo",
        "src": "img/alejo-logo.png",
        "srcDark": "img/logo2.png"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "🧭 Roadmaps",
          "position": "left",
          "items": [
            {
              "to": "/docs/ai-engineer/",
              "label": "🤖 AI Engineer"
            },
            {
              "to": "/docs/ai-architect/",
              "label": "🏗️ AI Architect"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "📚 Resources",
          "position": "left",
          "items": [
            {
              "to": "/docs/referencias/tools-stack",
              "label": "References"
            },
            {
              "to": "/docs/referencias2/tools-stack2",
              "label": "Projects"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "AI Engineer",
          "items": [
            {
              "label": "Advanced Python",
              "to": "/docs/ai-engineer/python-avanzado"
            },
            {
              "label": "LLMs & Transformers",
              "to": "/docs/ai-engineer/llms-transformers"
            },
            {
              "label": "RAG and Embeddings",
              "to": "/docs/ai-engineer/rag-embeddings"
            },
            {
              "label": "Fine-tuning y PEFT",
              "to": "/docs/ai-engineer/fine-tuning-peft"
            }
          ]
        },
        {
          "title": "AI Architect",
          "items": [
            {
              "label": "Clean Architecture",
              "to": "/docs/ai-architect/clean-architecture"
            },
            {
              "label": "RAG Architecture",
              "to": "/docs/ai-architect/rag-architecture"
            },
            {
              "label": "GPU Infrastructure",
              "to": "/docs/ai-architect/gpu-infrastructure"
            },
            {
              "label": "AI Governance",
              "to": "/docs/ai-architect/ai-governance"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Tools & Stack",
              "to": "/docs/referencias/tools-stack"
            },
            {
              "label": "Sources",
              "to": "/docs/referencias/fuentes"
            }
          ]
        },
        {
          "title": "Resources 2",
          "items": [
            {
              "label": "Tools & Stack",
              "to": "/docs/referencias2/tools-stack2"
            },
            {
              "label": "Sources",
              "to": "/docs/referencias2/fuentes2"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Documentation. Alejo."
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "yaml",
        "json",
        "typescript",
        "docker"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexBlog": false,
        "docsRouteBasePath": "/docs"
      }
    ]
  ],
  "plugins": [],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
